name: numpyro10_torch
channels:
  - pytorch
  - intel
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - arviz=0.14.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.2
  - boost-cpp=1.78.0
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.0
  - cfitsio=4.2.0
  - cftime=1.6.2
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - common_cmplr_lic_rt=2021.4.0
  - conda=4.14.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - contourpy=1.0.6
  - cryptography=39.0.2
  - curl=7.88.1
  - cycler=0.11.0
  - daal4py=2021.7.1
  - dal=2021.7.1
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.6
  - dpcpp_cpp_rt=2021.2.0
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.5.0
  - fftw=3.3.9
  - fiona=1.8.22
  - fmt=9.1.0
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.6.1
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icc_rt=2021.2.0
  - icu=70.1
  - idna=3.4
  - importlib_resources=5.2.0
  - intel-cmplr-lic-rt=2022.2.1
  - intel-openmp=2021.4.0
  - intelpython=2022.2.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jax=0.3.25
  - jaxlib=0.3.25
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.0.1
  - jpeg=9e
  - json-c=0.16
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=13.0.1
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.6.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libgrpc=1.51.1
  - libiconv=1.17
  - libkml=1.3.0
  - libllvm13=13.0.1
  - libmamba=1.3.1
  - libmambapy=1.3.1
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.2
  - libprotobuf=3.21.12
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libsolv=0.7.23
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=15.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.3.1
  - mapclassify=2.5.0
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multipledispatch=0.6.0
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf4=1.6.2
  - networkx=3.0
  - notebook=6.4.11
  - nspr=4.35
  - nss=3.89
  - numpy=1.23.4
  - numpy-base=1.23.4
  - numpyro=0.10.1
  - openjpeg=2.5.0
  - openssl=3.1.0
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - ply=3.11
  - poppler=22.12.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - proj=9.1.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.8
  - pytorch=1.12.1
  - pytz=2022.6
  - pyzmq=22.3.0
  - qt=5.15.8
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - re2=2023.02.01
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.28.2
  - rtree=1.0.1
  - ruamel_yaml=0.15.80
  - scikit-learn=0.24.2
  - scikit-learn-intelex=2021.7.1
  - scipy=1.9.3
  - send2trash=1.8.0
  - setuptools=65.5.0
  - shapely=2.0.1
  - sip=6.7.7
  - six=1.16.0
  - snappy=1.1.10
  - soupsieve=2.3.1
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tbb=2021.7.1
  - terminado=0.13.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tiledb=2.13.2
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing_extensions=4.4.0
  - tzcode=2022g
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xarray=2022.11.0
  - xarray-einstats=0.3.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.2.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
    - funsor==0.4.4
    - makefun==1.15.0
