name: numpyro10_torch
channels:
  - pytorch
  - intel
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - arviz=0.14.0
  - dill=0.3.6
  - intel-cmplr-lic-rt=2022.2.1
  - intel-openmp=2021.4.0
  - intelpython=2022.2.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jax=0.3.25
  - jaxlib=0.3.25
  - jpeg=9e
  - json-c=0.16
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - mapclassify=2.5.0
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.2
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - netcdf4=1.6.2
  - networkx=3.0
  - notebook=6.4.11
  - numpy=1.23.4
  - numpy-base=1.23.4
  - numpyro=0.10.1
  - pandas=1.5.2
  - pickleshare=0.7.5
  - python=3.8.16
  - python_abi=3.8
  - pytorch=1.12.1
  - scikit-learn=0.24.2
  - scikit-learn-intelex=2021.7.1
  - scipy=1.9.3
  - shapely=2.0.1
 
